<?php
// $Id$

define('VID_NUMERITHEQUE',10);

///////////////////////////////////////////////////////////////////////////////////
// HOOKS
///////////////////////////////////////////////////////////////////////////////////


/**
* Implements hook_block_info().
*/
function mnhn_numeritheque_block_info() {
  
 
  
   $blocks['menu_numeritheque'] = array(
    'info' => t('Menu numeritheque'),
    'status' => TRUE,
    'region' => 'sidebar_first',
    'weight' => 0,
    'visibility' => 1,
  );
  
  $blocks['search_numeritheque'] = array(
    'info' => t('Recherche Numérithèque'),
    'status' => TRUE,
    'region' => 'sidebar_first',
    'weight' => 1,
    'visibility' => 1,
  );
  
  
   
  
 
 
  return $blocks;
}



/**
* Implements hook_block_view().
*/
function mnhn_numeritheque_block_view($delta = '') {
  switch ($delta) {
 
 
  
   case 'menu_numeritheque':
    //$block['subject'] = '';
   
   		
    	 $block['content'] = mnhn_numeritheque_menu_vertical();
   		 return $block;
   	 
  break;
  
  
  case 'search_numeritheque':
    //$block['subject'] = '';
    $block['content'] = drupal_get_form('mnhn_numeritheque_search_form');
    return $block;
  
  
  }
}


/**
 * Implementation of hook_node_view()
 */
function mnhn_numeritheque_node_view($node, $view_mode, $langcode) {
	global $language;
	if($node->type=='numeritheque'){
		
		$breacrumb=array();
		$breacrumb[]=l(t('Home'), '');
		$breacrumb[]=l(t('Exhibitions'), 'expositions');
		
		drupal_set_breadcrumb($breacrumb);
	}
}


/**
 * Implementation of hook_theme()
 */
function mnhn_numeritheque_theme(){
	return array(

			'menu-xl-item-numeritheque' => array(
					'variables' => array('numeritheque' => NULL),
					'template' => 'menu-xl-item-numeritheque'),
	);

}



/**
 * Implementation of hook_menu().
 */
function mnhn_numeritheque_menu() {

	$items['numeritheque'] = array(
			'title' => 'Numérithèque',
			'page callback' => 'mnhn_numeritheque_liste',
			'page arguments' => array(''),
			'access arguments' => array('access content'),
			'type' => MENU_NORMAL_ITEM,
	);


	return $items;
}


///////////////////////////////////////////////////////////////////////////////////
// NUMERITHEQUE
///////////////////////////////////////////////////////////////////////////////////


/**
 * Menu vertical
 * 
 *
 */
function mnhn_numeritheque_menu_vertical(){
	global $language;
	
	
		
	
		$sql = 'SELECT name,tid from taxonomy_term_data where vid=:vid order by weight asc';
		$result=db_query($sql,array(':vid' => VID_NUMERITHEQUE));
		
		
		//$output.='<div class="exposition-liste">';
		$list=array();
		if(arg(0)=='numeritheque' && arg(1)==''){
				$class='activ';
		}
		$list['items'][]=array('data' => '<a href="/'.drupal_get_path_alias('numeritheque').'">'.t('View all multimedia resources').'</a>'.$links, 'class' => $class);
		$events=0;
		foreach($result as $row){
			$class='';
			if(arg(0)=='numeritheque' && arg(1)==$row->tid){
					$class='activ';
			}
			$term=taxonomy_term_load($row->tid);
			$term_translate=i18n_taxonomy_term_name($term, $language->language);
		
			$list['items'][]=array('data' => '<a href="/'.drupal_get_path_alias('numeritheque/'.$row->tid).'">'.$term_translate.'</a>'.$links, 'class' => $class, 'rel' => $row->tid);
		}	
		

		
		
		
	
	
	$list['title']=t('Multimedia resources');
	$list['attributes']['class']='menu-vertical';
	$output = theme('item_list',$list);
	return $output;
	
		
}










/**
 * Liste des ressources
 *
 * @param $search => string
 *
 */
function mnhn_numeritheque_liste($search=NULL){
	
	
	if(arg(1)=='search'){
		$search=arg(2);
	}
	
	global $language;
	
	$breacrumb=array();
	$breacrumb[]=l(t('Home'), '');
	$breacrumb[]=l(t('Multimedia resources'), 'numeritheque');
	drupal_set_breadcrumb($breacrumb);
	
	$query=db_select('node','n')->extend('PagerDefault');
	$query->fields('n',array('nid'));
	$query->condition('type','ressource');
	$query->condition('n.language',$language->language);
	$query->condition('n.status',1);
	
	if(arg(1)>0){
			$query->innerJoin('taxonomy_index', 'ti', 'ti.nid=n.nid');
			$query->condition('ti.tid',arg(1),'=');
	}	
	if(!empty($search)){
		$db_or = db_or();
	    $db_or->condition('n.title', '%' . db_like($search) . '%', 'LIKE');
	    //$db_or->condition('a.field_blog_accroche_value', '%' . db_like($search) . '%', 'LIKE');
	    $query->condition($db_or);
		
	}
	
	$query->orderBy('n.created','DESC');
	$query->limit(6);
	$result=$query->execute();
	
	
	$i=0;
	foreach($result as $row){
		$node=node_load($row->nid);
		$ressources.=drupal_render(node_view($node, 'teaser'));
		$i++;
		
		
	}
	
	
	if(!empty($search)){
		
		$title_ressource=t('Your search <em>!search</em>: !results result(s)',array('!search' => $search,'!results'=> $i));
	}else{
		if(arg(1)>0){
			$title_ressource=mnhn_content_get_term(arg(1));
		}else{
			$title_ressource=t('View all multimedia resources');
		}
		
	}
		$output='<div class="numeritheque-header">
                    
                        <h1 class="title_m">'.$title_ressource.' </h1>

                    </div><div class="page-detail-wrapper">';
		$output.=theme('pager');
	    $output.='<div id="all-products">';
		$output.=$ressources;
		$output.='</div>';
		$output.=theme('pager');
		$output.='</div>';
		
	return $output;
	
	
	
}


/**
 * Blocs ressources associés
 *
 * @param $tab => liste nid associés
 *
 */
function mnhn_numeritheque_liste_link($tab=array()){
	
	global $language;
	if(sizeof($tab)){
		foreach($tab as $value){
			$tab_nids[]=$value['nid'];
			
		}
		
		$nids = implode(",", $tab_nids);
		
		
		
		$sql = 'SELECT n.nid FROM node n
		where n.language=:language and n.status=:status and n.nid in ('.$nids.')
		order by n.title asc';
		$result=db_query($sql,array(':language'=> $language->language,':status'=> 1));
		
		foreach($result as $row){
			$node=node_load($row->nid);
			$ressources.=drupal_render(node_view($node, 'teaser'));
			$i++;
		}
		
		$output='<div id="cross-selling"><h2>'.t('Related resources').'</h2>';
		$output.=$ressources;
		$output.='</div>';
	
		return $output;
	}
	
	
}

/*
 * 
 * Formulaire de recherche
 * 
 */
function mnhn_numeritheque_search_form(){

	$form['content'] = array(
			'#title' => t('Search and find'),
			'#type' => 'textfield',
			'#size' => '18',
			'#maxlength' => '132',
	);

	$form['submit'] = array(
			'#type' => 'submit',
			'#value' => t('OK')
	);

	return $form;
}


/**
 * Handle post-validation form submission.
 */
function mnhn_numeritheque_search_form_submit($form_id, $form_state) {

	$search = $form_state['values']['content'];
	$search=strip_tags($search);
	drupal_goto("numeritheque/search/".$search);
	 
}




///////////////////////////////////////////////////////////////////////////////////
// MENU XL
///////////////////////////////////////////////////////////////////////////////////



function mnhn_numeritheque_menu_xl(){
	
	global $language;
	$mlid_numeritheque=constant("MLID_NUMERITHEQUE_".strtoupper($language->language));
	
	//$link=menu_link_load($mlid_collection);
	
	
	$menu_collection=menu_tree_all_data("menu-menu-principal");
	
	foreach($menu_collection as $item){
		if($item['link']['language']==$language->language && $item['link']['mlid']==$mlid_numeritheque){
				
			
					foreach($item['below'] as $item_child){
						$title=$item_child['link']['link_title'];
						$uri=variable_get('menu_image_'.$item_child['link']['mlid'],'');
						$description=variable_get('menu_text_'.$item_child['link']['mlid'],'');
						$image='';
						if(!empty($uri)){
							$image=theme('image_style', array('style_name' => 'menu', 'path' => variable_get('menu_image_'.$item_child['link']['mlid'],'')));
						}
						$main_link=$item_child['link']['link_path'];
						$links = l(t('More information'),$item_child['link']['link_path'],array('attributes' => array('class' => array('link'))));
			
						$output.=theme('menu-xl-item', array('main_link' => $main_link,'image' => $image, 'title' => $title, 'description' => $description, 'links'=> $links));
						
					
				}
			
		}
   }
	
  
	return $output;
	
	
	
}


///////////////////////////////////////////////////////////////////////////////////
// PREPROCESS
///////////////////////////////////////////////////////////////////////////////////

/**
 * Override or insert variables into the page templates.
 *
 * @param $variables
 *   An array of variables to pass to the theme template.
 * @param $hook
 *   The name of the template being rendered ("page" in this case.)
 */
function mnhn_numeritheque_preprocess_html(&$variables, $hook) {
	
 	if(arg(0)=='numeritheque' || (arg(0)=='node' && mnhn_content_get_content_type(arg(1))=='ressource')  ){
 		
 		$variables['classes_array'][] = "numeritheque";
 		
 		
 	}
 	
 	if(arg(0)=='taxonomy'){
 			
 		$variables['classes_array'][] = "numeritheque";
 			
 			
 	}
 	
 	$variables['classes'] = implode(' ', $variables['classes_array']);
 	
}









function mnhn_numeritheque_taxonomy_term_presave($term){
	if($term->vid==VID_NUMERITHEQUE){
		module_load_include('inc', 'pathauto', 'pathauto');
		db_query('delete from url_alias where source=:source',array(':source' => 'numeritheque/'.$term->tid));
		path_save($a = array('source' => 'numeritheque/'.$term->tid, 'alias' => 'numeritheque/'.pathauto_cleanstring($term->name), 'pid' => $pid, 'language'=>'fr'));
	}
}



